const programsData = [
  {
    id: 1,
    title: 'Biochemistry programs',
    isOpen: false,
    courses: [
      'Bilirubin neonatal',
      'Blood Gas and Electrolytes',
      'Cardiac Marker',
      'Cerebrospinal Fluid',
      'Clinical Chemistry',
      'Coagulation',
      'Co-Oximetry',
      'Drugs of Abuse',
      'Ethanol, Ammonia and Bicarbonate',
      'Fecal Occult Blood',
      'Glycated Hemoglobin',
      'Prothrombin time (POCT)',
      'Qualitative Urine Analysis (Urine stick)',
      'Therapeutic Drugs',
      'Urine Chemistry',
      'Urine Sediments for microscopic methods',
      'Urine Sediments for light scattering methods',
    ],
  },
  {
    id: 2,
    title: 'Immunology Programs',
    isOpen: false,
    courses: [
      'hCG',
      'Hormones',
      'Procalcitonin',
      'Specific Proteins',
      'Thyroid Antibodies',
      'Tumor Marker',
      'Tumor Marker & Hormones',
    ],
  },
  {
    id: 3,
    title: 'Microbiology Programs',
    isOpen: false,
    courses: [
      'Adenovirus',
      'Aspergillus Fumigatus',
      'Aspergillus Galactomannan Antigen',
      'Bacteriology',
      'Borrelia',
      'Borrelia IgM antibody index',
      'Brucella',
      'Chagas',
      'Chikungunya Virus',
      'Chlamydia Trachomatis',
      'Coxsackievirus',
      'Dengue Virus',
      'ECHO-Virus',
      'Enterovirus',
      'Epstein-Barr Virus',
      'Hepatitis A Virus',
      'Hepatitis B Virus',
      'Hepatitis E Virus',
      'HIV Antibodies and Antigen',
      'HTLV I/II',
      'Infectious Disease Combination Control',
      'Influenza A Virus',
      'Influenza B Virus',
      'Legionella Pneumophila Antibodies',
      'Leptospira',
      'Malaria Microscopy',
      'Measles',
      'Parainfluenza Virus',
      'Parvovirus B19',
      'Respiratory Syncytial Virus',
      'SARS-CoV-2 Antibodies',
      'SARS-CoV-2 Antigen',
      'Syphilis',
      'TBEV IgG antibody index',
      'TBEV IgM antibody index',
      'ToRCH',
      'Varicella Zoster Virus',
      'West Nile Virus',
      'Zika Virus',
    ],
  },
  {
    id: 4,
    title: 'Molecular Diagnostics Programs',
    isOpen: false,
    courses: [
      'HBV Molecular',
      'HCV Molecular',
      'HIV Molecular',
      'SARS-CoV-2 Molecular',
    ],
  },
  {
    id: 5,
    title: 'Hematology Programs',
    isOpen: false,
    courses: [
      'Blood grouping',
      'Immunohematology',
      'Erythrocyte Sedimentation Rate Alcor',
      'Erythrocyte Sedimentation Rate Alifax',
      'Erythrocyte Sedimentation Rate',
      'Hemogram',
      'Hemogram incl. 3-Part Diff.',
      'Hemogram incl. 5-Part Diff.',
    ],
  },
  {
    id: 6,
    title: 'Educational Programs',
    isOpen: false,
    courses: ['Clinical Case Study Program'],
  },
];

export default programsData;
