const programsArray = [
  {
    id: 1,
    title: 'Biochemistry programs',
    isOpen: false,
    courses: [
      'Bilirubin neonatal',
      'Blood Gas and Electrolytes',
      'Cardiac Marker',
      'Cerebrospinal Fluid',
      'Clinical Chemistry',
      'Coagulation',
      'Co-Oximetry',
      'Drugs of Abuse',
      'Ethanol, Ammonia and Bicarbonate',
      'Fecal Occult Blood',
      'Glycated Hemoglobin',
      'Prothrombin time (POCT)',
      'Qualitative Urine Analysis (Urine stick)',
      'Therapeutic Drugs',
      'Urine Chemistry',
      'Urine Sediments for microscopic methods',
      'Urine Sediments for light scattering methods',
    ],
  },
  {
    id: 2,
    title: 'Immunology Programs',
    isOpen: false,
    courses: [
      'hCG',
      'Hormones',
      'Procalcitonin',
      'Specific Proteins',
      'Thyroid Antibodies',
      'Tumor Marker',
      'Tumor Marker & Hormones'
    ],
  },
  {
    id: 3,
    title: 'Microbiology Programs',
    isOpen: false,
    courses: [
      'Adenovirus',
      'Aspergillus Fumigatus',
      'Aspergillus Galactomannan Antigen',
      'Bacteriology',
      'Borrelia',
      'Borrelia IgM antibody index',
      'Brucella',
      'Chagas',
      'Chikungunya Virus',
      'Chlamydia Trachomatis',
      'Coxsackievirus',
      'Dengue Virus',
      'ECHO-Virus',
      'Enterovirus',
      'Epstein-Barr Virus',
    ],
  },
];

export default programsArray;